### ISSUE TITLE
[Pytorch] BERT 모델 최적화 reference

### ISSUE THREAD

**Issue by plaire48** [GirinMan/HYU-Graduation-Project-Quantization#4]
Pytorch를 사용해 BERT 모델을 최적화하는데 필요한 Reference를 정리했습니다.
졸업프로젝트 주간 모임을 통해 공부할 예정입니다.

1. [이론] 여러 quantization 방법
- https://jin-choi.tistory.com/18

2. [Pytorch] BERT 소스 코드 이해
- https://hyen4110.tistory.com/87

3. [Pytorch 튜토리얼] BERT 모델 동적 양자화하기
- https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/dynamic_quantization_bert_tutorial.ipynb
-  https://tutorials.pytorch.kr/intermediate/dynamic_quantization_bert_tutorial.html#

4. [Pytorch 튜토리얼] PYTORCH에서 EAGER MODE를 이용한 정적 양자화
- https://tutorials.pytorch.kr/advanced/static_quantization_tutorial.html#

**Comment by GirinMan** [comment]
- 올려져 있는 튜토리얼 코드를 코랩이나 로컬에서 직접 실행해보고 실행 결과와 느낀 점(잘 안 되었을 경우 안 되는 부분이나 앞으로 추가로 더 진행하면 좋을 것 같은 부분) 정리해서 커밋하면 좋을 듯...
- 연구실에서 제공한 서버(https://github.com/GirinMan/HYU-Graduation-Project-Quantization/issues/6)로 Jupyter notebook 서버 열어두고 외부 접속 가능한지 테스트해보고 알려주겠습니다

**Comment by GirinMan** [comment]
### Colab 환경에서 노트북 실행 시 라이브러리 버전으로 인한 오류
#### 2.3. Define the tokenize and evaluation function 부분
- load_and_cache_examples 함수에서 convert_examples_to_features 함수에 들어가는 keyword args가 최신 버전과 다름
- 일부 삭제해야 오류 없이 작동하므로 아래와 같이 코드 수정해서 실행해볼 것

**기존**
```
        features = convert_examples_to_features(examples,
                                                tokenizer,
                                                label_list=label_list,
                                                max_length=args.max_seq_length,
                                                output_mode=output_mode,
                                                pad_on_left=bool(args.model_type in ['xlnet']),                 # pad on the left for xlnet
                                                pad_token=tokenizer.convert_tokens_to_ids([tokenizer.pad_token])[0],
                                                pad_token_segment_id=4 if args.model_type in ['xlnet'] else 0,
        )
```
**수정 후**
```
        features = convert_examples_to_features(examples,
                                                tokenizer,
                                                label_list=label_list,
                                                max_length=args.max_seq_length,
                                                output_mode=output_mode,
        )
```

**Comment by GirinMan** [comment]
- Quantization 관련 좋은 블로그 포스트가 하나 더 있어 공유합니다.
https://gaussian37.github.io/dl-concept-quantization/#qat-quantization-aware-training-%EB%B0%A9%EB%B2%95-1
